baseURL = "http://example.org/"
languageCode = "en-us"
title = "Website Name"
theme = "accessible-minimalism"
disableHugoGeneratorInject = true
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/rkingett/accessible-writer"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2